### ISSUE TITLE
Help with logs and metrics

### ISSUE THREAD

**Issue by igorvpcleao** [negz/draino#10]
Hi there,

I've been trying draino out, but I'm not able to collect its metrics nor see its logs.

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    component: draino
  name: draino
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: draino
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: draino
      name: draino
      namespace: kube-system
    spec:
      containers:
      - args:
        - --debug
        - --listen=:10002
        - KernelDeadlock
        - DiskPressure
        - PIDPressure
        command:
        - /draino
        image: negz/draino:abf028a
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10002
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: draino
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: draino
      serviceAccountName: draino
      terminationGracePeriodSeconds: 30
```
`kubectl logs` shows nothing and `curl localhost:10002/metrics` is empty as well. Not sure if I'm using it incorrectly, though. 

Thanks!
